name: Snapshot diff
on:
  push:
    branches:
      - main
jobs:
  snapshot-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: diff
        run: |
          if git diff HEAD^ HEAD packages/react/__tests__/__snapshots__/PublicAPI-test.js.snap
          then
             echo "New changes"
             echo git diff HEAD^ HEAD packages/react/__tests__/__snapshots__/PublicAPI-test.js.snap
          else
            echo "Nothing new"
          fi
