name: Snapshot diff
on:
  push:
    branches:
      - main
jobs:
  snapshot-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: diff
        run: |
          if git diff HEAD^ HEAD
          then
             echo "no changes"
             git diff HEAD^ HEAD --color > foo.txt
          else
            echo "got changes"
            git diff HEAD^ HEAD --color > foo.txt
          fi
