name: Snapshot diff
on:
  push:
    branches:
      - main
jobs:
  snapshot-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: diff
        run: |
          if git diff HEAD^ HEAD packages/react/__tests__/__snapshots__/PublicAPI-test.js.snap
          then
             echo "New changes"
             echo "diff=true" >> "$GITHUB_ENV"
             echo git diff HEAD^ HEAD packages/react/__tests__/__snapshots__/PublicAPI-test.js.snap
          else
            echo "Nothing new"
            echo "diff=false" >> "$GITHUB_ENV"
          fi
      - name: on-success
        if: env.diff == 'true'
        id: slack-success
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "diff": "The ${{ github.event.workflow.name }} workflow succeeded: ${{ github.event.workflow_run.url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: on-failure
        if: env.diff == 'false'
        id: slack-failure
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "diff": "no diff",
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
